import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import "./main.scss";
import Navbar from "./_components/(shared)/Navbar/Navbar";
import Footer from "./_components/(shared)/Footer/Footer";
import ReduxProvider from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Info Games",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
